apiVersion: apps/v1
kind: Deployment
metadata:
  name: yesonit-cdrm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yesonit-cdrm
  template:
    metadata:
      labels:
        app: yesonit-cdrm
    spec:
      containers:
      - name: yesonit-cdrm
        image: australia-southeast1-docker.pkg.dev/pure-particle-459712-s5/yesonit-cdrm/yesonit-cdrm:latest
        ports:
        - containerPort: 8087
      imagePullSecrets:
      - name: gcr-json-key